🇧🇷 [ Issue ##5855 ] change tests methods names to english
betrybe/sd-0x-restaurant-orders pull request #13
Opened 2021-11-09 20:20 UTC by tiagaoalb

Closes [Issue #5855](https://github.com/betrybe/course/issues/5855)

2021-11-09 20:33 UTC, vbuxbaum commented
@tiagaoalb o PR está disponível pra que eu mergeie (sem aprovação / code-review). Você consegue ajustar essa permissão?

Pra mergear na master do template deveria ser necessário 2 aprovações

2021-11-09 20:37 UTC, isquicha requested changes
Tem que fazer o `de -> para` no `.trybe/requirements.json`.

2021-11-09 21:23 UTC, tiagaoalb commented
> @tiagaoalb o PR está disponível pra que eu mergeie (sem aprovação / code-review). Você consegue ajustar essa permissão?
> 
> Pra mergear na master do template deveria ser necessário 2 aprovações

Pedi pro @renatofreire nos ajudar com essa questão porque não tenho permissão para isso.

2021-11-09 21:30 UTC, vbuxbaum approved these changes

2021-11-10 08:04 UTC, isquicha approved these changes
Depois de mergear, disponibiliza em staging e roda as implementações pra ver se tudo passa.
Se precisar de ajuda me chama no slack!

2021-11-10 12:20 UTC, merged